repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.11  # Använd samma version som din Ruff-installation
    hooks:
      - id: ruff
        args: [--fix, --select=I]
        types_or: [python, pyi, jupyter]
  - repo: https://github.com/psf/black
    rev: 25.1.0  # Kontrollera senaste versionen
    hooks:
      - id: black