version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: ducklake-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: duckuser
      POSTGRES_PASSWORD: duckpass
      POSTGRES_DB: postgres
      PGDATA: /pgdatabase
    volumes:
      - pgdata:/pgdatabase         # <— named volume
    ports:
      - "6543:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
      PGADMIN_DEFAULT_USER: admin
    ports:
      - "8080:80"

volumes:
  pgdata:
